#include "cr/content/levels.hpp"

#include <algorithm>
#include <cstddef>

#include "content_levels.hpp"  // generated by tools/gen_content.py

namespace game {
namespace {

const content::generated::LevelDef& Def(int index) {
  const int n = static_cast<int>(content::generated::kLevels.size());
  const int i = std::clamp(index, 0, n - 1);
  return content::generated::kLevels[static_cast<std::size_t>(i)];
}

}  // namespace

int LevelCount() {
  return static_cast<int>(content::generated::kLevels.size());
}

std::span<const std::string_view> LevelMap(int index) { return Def(index).map; }

WeatherConfig LevelWeather(int index) {
  const content::generated::LevelDef& d = Def(index);
  return WeatherConfig{.rain_rate = d.rain_rate,
                       .wind_base = d.wind_base,
                       .gust = d.gust,
                       .snow = d.snow,
                       .fog = d.fog};
}

std::string_view LevelName(int index) { return Def(index).name; }

}  // namespace game
